
# Configuration commune Ã  tous les services
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  security:
    user:
      name: ${CONFIG_SERVER_USERNAME:oumaima}
      password: ${CONFIG_SERVER_PASSWORD:oumaima}
    registry:
      address: localhost
      port: 8761
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/portail-mcp}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8080/realms/portail-mcp/protocol/openid-connect/certs}
  # Eureka Client
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
      register-with-eureka: true
      fetch-registry: true


# Keycloak Configuration
keycloak:
  server:
    url: ${KEYCLOAK_SERVER_URL:http://localhost:8080}
    realm: ${KEYCLOAK_REALM:portail-mcp}
    client-id: ${KEYCLOAK_CLIENT_ID:frontend}
    client-secret: ${KEYCLOAK_CLIENT_SECRET:q4OfuRbgGj1Ckr3Tj5vWHYUQZDSsmFTw}


logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG


