server:
  port: 8000
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file://C:/workDeepMCP/configuration
          default-label: main
          clone-on-start: false
          search-paths: ${spring.profiles.active}
    security:
      user:
        name: ${CONFIG_SERVER_USERNAME:oumaima}
        password: ${CONFIG_SERVER_PASSWORD:oumaima}